<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SvgIcons $icons */
/** @var PaymentIconsLight $paymentIcons */
/** @var ViewModelRegistry $viewModels */

$icons = $viewModels->require(SvgIcons::class);
$paymentIcons = $viewModels->require(PaymentIconsLight::class);
?>
<div class="bg-neutral-600 text-gray-600 text-base leading-6">
    <div class="text-center py-8 flex gap-4 flex-wrap justify-center container mx-auto px-7 ">
        <?= $paymentIcons->idealHtml('', 48, 32) ?>
        <?= $paymentIcons->visaHtml('', 48, 32) ?>
        <?= $paymentIcons->mastercardHtml('', 48, 32) ?>
        <?= $paymentIcons->paypalHtml('', 48, 32) ?>
        <?= $paymentIcons->klarnaHtml('', 48, 32) ?>
        <?= $paymentIcons->applePayHtml('', 48, 32) ?>
        <?= $paymentIcons->googlePayHtml('', 48, 32) ?>
        <?= $paymentIcons->bitcoinHtml('', 48, 32) ?>
    </div>

    <div class="bg-neutral-700 py-8 border-b border-gray-300">
        <div class="container mx-auto px-7">
            <ul class="font-bold flex flex-col items-center md:flex-row md:justify-around text-neutral-200">
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Sign In')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('order-returns')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Order & Returns')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('confirmpayment')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Confirm Payment')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('sales/guest/form')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Tracking Order')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('story')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Story')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('contact-form')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('Contact Us')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= $escaper->escapeUrl($block->getUrl('faq')) ?>"
                        class="hover:underline"
                    >
                        <?= $escaper->escapeHtml(__('FAQ')) ?>
                    </a>
                </li>
            </ul>
            <div class="flex justify-center gap-4 mt-8 text-gray-700">
                <a href="#" class="hover:opacity-80">
                    <?= $icons->renderHtml('social-facebook', '', 32, 32, ['aria-hidden' => 'true']) ?>
                </a>
                <a href="#" class="hover:opacity-80">
                    <?= $icons->renderHtml('social-instagram', '', 32, 32, ['aria-hidden' => 'true']) ?>
                </a>
                <a href="#" class="hover:opacity-80">
                    <?= $icons->renderHtml('social-pinterest', '', 32, 32, ['aria-hidden' => 'true']) ?>
                </a>
                <a href="#" class="hover:opacity-80">
                    <?= $icons->renderHtml('social-twitter', '', 32, 32, ['aria-hidden' => 'true']) ?>
                </a>
            </div>

        </div>
    </div>
    <div class="py-8 bg-neutral-700">
        <div class="container mx-auto px-7 text-center text-sm">
            <div class="text-gray-500">
                <?= $escaper->escapeHtml(__('© 2022 Hyvä')) ?> -
                <?php /* Enable the following line to show the copyright information configured in the admin
                <?= $escaper->escapeHtml($block->getCopyright()) ?>
                */ ?>
                <a
                    class="hover:underline"
                    href="<?= $escaper->escapeHtmlAttr('https://twitter.com/hyva_io') ?>"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <?= $escaper->escapeHtml(__('@hyva_io')) ?>
                </a>
            </div>
            <div class="text-gray-400 mt-4">
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                    class="hover:underline"
                >
                    <?= $escaper->escapeHtml(__('Terms & Conditions')) ?>
                </a> |
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                    class="hover:underline"
                >
                    <?= $escaper->escapeHtml(__('Privacy Policy')) ?>
                </a>
            </div>
        </div>
    </div>
</div>
